


app_api_v1_user:
    type: rest
    prefix: /v1
    resource: AppBundle\Controller\Api\V1\UserController
    name_prefix:  api_1_user


app_api_v1_messenger:
    type: rest
    prefix: /v1
    resource: AppBundle\Controller\Api\V1\MessengerController
    name_prefix:  api_1_messenger
